### ISSUE TITLE
Create a sample template in React, Vue and NextJS

### ISSUE THREAD

**Issue by dharanigowthamsampath** [editor-js/header#107]
its really hard to understand the documentation for the beginners, who is willing to use EditorJS. it will be Good if we have the pre-build templates for those who is absolute for beginner

**Comment by neSpecc** [comment]
Sure, it would be helpful. But there this issue is not related to the Header Tool.

Also, here is an example of Vue.js component:
https://github.com/codex-team/notes.web/blob/main/codex-ui/src/vue/components/editor/Editor.vue
