### ISSUE TITLE
You broke it

### ISSUE THREAD

**Issue by VityaSchel** [editor-js/header#112]
Getting `TypeError: Cannot read properties of undefined (reading 'toString')` in next.js with react-editor-js

<img width="811" alt="image" src="https://github.com/editor-js/header/assets/59040542/8cebe679-bc2e-44da-9a03-0a5f822e124b">
 fuck and I thought why it does not work for me and works for everyone else :cry:

**Comment by Aryanop0914** [comment]
broo it worked yesterday today it was broke thought same..😂

**Comment by bckmnn** [comment]
last working version for me is `v2.8.1` all newer ones throw an error. (i am using typescript)
