### ISSUE TITLE
No ability to provide available levels

### ISSUE THREAD

**Issue by proArtex** [editor-js/header#14]
It seems like levels are hardcoded and cannot be set. What if I want to put H1 only?

**Comment by Farrien** [comment]
Wait. So how to allow/disallow header types?

**Comment by talyguryn** [comment]
Sorry, my bad

**Comment by nynevi** [comment]
ugly but works:

```
    .cdx-settings-button[data-level='1'],
    .cdx-settings-button[data-level='4'],
    .cdx-settings-button[data-level='5'],
    .cdx-settings-button[data-level='6'] {
      display: none;
    }
```

I used the same method for hiding image options but it had an explicity classname so using the above method with -settings- might break other plugin options that has levels
```
.image-tool__tune {
     display: none;
}
```

**Comment by igorivaniuk** [comment]
Or extend Header class

```ts
class MyHeader extends Header {
  get levels() {
    return super.levels.filter((l: any) => [2, 3, 4].includes(l.number));
  }

  get defaultLevel() {
    /**
     * Use H2 as default header
     */
    return this.levels[0];
  }
}
```

![editorjs](https://user-images.githubusercontent.com/1407909/59446976-34046b00-8e0b-11e9-894f-6ca3d0e5f0a7.png)

**Comment by zizther** [comment]
Would like to see this built in as a option

**Comment by damien-monni** [comment]
I agree, it would be nice!

**Comment by sandrooco** [comment]
@igorivaniuk Extending like you did doesn't work for me:

> Type 'typeof CustomHeading' is not assignable to type 'BaseToolConstructable'.
>                   Property 'render' is missing in type 'CustomHeading' but required in type 'BaseTool'.
If I use `heading: CustomHeading as BaseToolConstructable,` it will build (and work..) but still throw an error in the terminal.

**Comment by neSpecc** [comment]
It can be done by adding a corresponding config option. You are welcome to implement this feature and send a PR.

**Comment by alexanderhorner** [comment]
Extending doesn't work for me

`SyntaxError: Unexpected token ':'. Expected ')' to end a compound expression.`
