### ISSUE TITLE
Update readme about supported settings levels

### ISSUE THREAD

**Issue by neSpecc** [editor-js/header#20]
We support 1—6 levels

<img width="817" alt="image" src="https://user-images.githubusercontent.com/3684889/55585546-95370080-572f-11e9-8810-a418433952cd.png">

**Comment by alexanderhorner** [comment]
How do I specify wich Headings I want to provide to the user? So lets say I want to remove H4 - H6 from the Block Settings, how would I do that? Something in the tool config?

**Comment by neSpecc** [comment]
@alexanderhorner Follow this issue https://github.com/editor-js/header/issues/14
