### ISSUE TITLE
Header is not styling itself

### ISSUE THREAD

**Issue by roncarino** [editor-js/header#22]
Hi everyone, 
first of all, thanks a lot for your hard work.

I have a Laravel project end I am integrating EditorJS and your header tool. This is my configuration so far:

```
const editor = new EditorJS( {
    /**
        * Id of Element that should contain Editor instance
        */
    holder: 'editorjs',
    /**
        * Tools list
        */
    tools: {
        header: {
            class: Header,
            inlineToolbar: [ 'link' ],
            config: {
                placeholder: 'Header'
            },
            shortcut: 'CMD+SHIFT+H'
        },
        /**
            * Or pass class directly without any configuration
            */
        image: {
            class: ImageTool,
            config: {
                uploader: {
                    /**
                        * Upload file to the server and return an uploaded image data
                        * @param {File} file - file selected from the device or pasted by drag-n-drop
                        * @return {Promise.<{success, file: {url}}>}
                        */
                    uploadByFile( file ) {
                        let formData = new FormData();
                        formData.append( 'file', file );

                        return new Promise( function ( resolve ) {
                            axios.post( '/admin/media', formData, {
                                headers: {
                                    'Content-Type': 'multipart/form-data'
                                }
                            } ).then( function ( response ) {
                                // The data from the request is available in a .then block
                                // We return the result using resolve.
                                resolve( response.data );
                            } ).catch( ( error ) => {
                                console.log( 'ERROR!!', error );
                            } ).then( () => {
                            } );
                        } )
                    },
                },
            },
        },
        list: {
            class: List,
            inlineToolbar: true,
            shortcut: 'CMD+SHIFT+L'
        },
        checklist: {
            class: Checklist,
            inlineToolbar: true,
        },
        quote: {
            class: Quote,
            inlineToolbar: true,
            config: {
                quotePlaceholder: 'Enter a quote',
                captionPlaceholder: 'Quote\'s author',
            },
            shortcut: 'CMD+SHIFT+O'
        },
        delimiter: Delimiter,
        embed: Embed,
        Marker: {
            class: Marker,
            shortcut: 'CMD+SHIFT+M',
        }
    },
} );
```

I am using Laravel mix (webpack) and extracting "@editorjs/editorjs" on my vendor.js file together with other libraries. Everything is looking good honestly. Only problem I am having is that the header is not "styling" itself when you choose it. Attached images:

<img width="657" alt="Schermata 2019-05-12 alle 18 17 24" src="https://user-images.githubusercontent.com/13092188/57579631-4c1e5d00-74e2-11e9-9620-b7b1dbf65b92.png">

Am I doing something wrong? I cannot really figure it out.

**Comment by roncarino** [comment]
I think I found the reason. I am using Bulma to build my project and somehow its css overwrite your "ce-header" css. Not entirely sure how to make this work now but at least I know the problem. I think I can close the issue. Thanks

<img width="657" alt="Schermata 2019-05-12 alle 18 17 24" src="https://user-images.githubusercontent.com/13092188/57588910-3733df00-755f-11e9-85ac-e88d719ad96e.png">

**Comment by AjeaSmith** [comment]
I'm having the same problem but I'm not using any css framework, just pure css

**Comment by roncarino** [comment]
> I'm having the same problem but I'm not using any css framework, just pure css

Umm that sounds quite odd honestly. Anyway, in my case, I have solved extending Header class and overwriting render function to add and extra wrapper around "h" element. Not sure if this can help you.

```
class MyHeader extends Header {
    /**
     * Return Tool's view
     * @returns {HTMLHeadingElement}
     * @public
     */
    render() {
        const extrawrapper = document.createElement('div');
        extrawrapper.classList.add('content');
        extrawrapper.appendChild(this._element);

        return extrawrapper;
    }
}
```

**Comment by Thimows** [comment]
I have the same problem. Dis any one find a good solution? Without headings this package is almost useless sadly ):

**Comment by dbwodlf3** [comment]
it works. but. if style not applyed. then you need to check h tags.
This tool use just pure css style. if you edit default h tag style, then applyed that style.

**Comment by Hotdogerino** [comment]
Fixed in NextJS/ChakraUI by adding a global stylesheet inside in _app.tsx file, the css looked like in this pen
https://codepen.io/adamlacombe/pen/LvpJqO

**Comment by stevie101** [comment]
Just experienced the same issue with Bulma. Found if you wrap the editorjs div with one that includes a content class it stopped overriding the heading tags.

`<div class="content"><div id="editorjs"></div></div>`

**Comment by MejanH** [comment]
in my case, tailwindcss removed the default browser heading styles. source: https://laracasts.com/discuss/channels/javascript/editorjs-inline-styles-overruled-by-tailwindcss

**Comment by PradhaID** [comment]
i need to add several styles on my css when using tailwindcss like :
```
h1.ce-header{
  @apply text-3xl font-bold
}
h2.ce-header{
  @apply text-2xl font-semibold
}
h3.ce-header{
  @apply text-xl font-semibold
}
h4.ce-header{
  @apply text-lg font-semibold
}
h5.ce-header{
  @apply text-base font-semibold
}
h6.ce-header{
  @apply text-base font-semibold
}
```

**Comment by trancethehuman** [comment]
Issue still exists with Tailwind 3.3.2 and editorjs 2.28

**Comment by OFD16** [comment]
> i need to add several styles on my css when using tailwindcss like :
> 
> ```
> h1.ce-header{
>   @apply text-3xl font-bold
> }
> h2.ce-header{
>   @apply text-2xl font-semibold
> }
> h3.ce-header{
>   @apply text-xl font-semibold
> }
> h4.ce-header{
>   @apply text-lg font-semibold
> }
> h5.ce-header{
>   @apply text-base font-semibold
> }
> h6.ce-header{
>   @apply text-base font-semibold
> }
> ```

![image](https://github.com/editor-js/header/assets/96663769/17eccad8-8ea2-4274-9bee-ab6d9866592a)

this solved my next.js tailwind website for editor.js problem thanks a lot

**Comment by code-march** [comment]
> Reference

Thank you Brother (Solved)

**Comment by raaam02** [comment]
@OFD16 
Thanks a lot it solved my problem
