### ISSUE TITLE
npm i --save-dev

### ISSUE THREAD

**Issue by atilkan** [editor-js/header#27]
Why do we need to save for dev? I would be needing this on runtime. 
Note: Other plugins documented the same way too.

**Comment by dimensi** [comment]
Because maintainers so wanted.

**Comment by atilkan** [comment]
@dimensi It is not about wanting. Thanks for your useful comment.

**Comment by dimensi** [comment]
I brought up the same topic with the maintainers and they said that after long discussions, they decided that it would be so.
They consider if the package does not fall as a separate package to the front, and as part of something, this means you need to use `--save-dev`

**Comment by atilkan** [comment]
@dimensi It must be bundled to core then.

**Comment by kasbah** [comment]
Looks like they will fix it for the editorjs docs: https://github.com/codex-team/editor.js/issues/730
