### ISSUE TITLE
Saving resets text formatting

### ISSUE THREAD

**Issue by gekh** [editor-js/header#44]
I can use hotkeys like SHIFT+ENTER, CMD+B in a Header block. But when I save it resets. All formatting disappears.

So it has different look in the editor and in final HTML.

How to make hotkeys unavailable in the Header block?

There is no such problem in block Code https://github.com/editor-js/code

**Comment by sonnn** [comment]
Facing the same issue and I think there is a workaround for this.

![image](https://user-images.githubusercontent.com/5780387/83941853-3a140880-a821-11ea-9f65-67694ffde558.png)

Note: I try for <mark> and <code> but they not work.
