### ISSUE TITLE
Custom inline icon override

### ISSUE THREAD

**Issue by NRiebesel** [editor-js/header#47]
Hi!

It's possible to override ICONs in the toolbar in the plugin config via the `toolbox` property. That works! But is it also possible to change it in the inline toolbar? Especially in the "convert to" dropdown?

**Comment by SnickTen** [comment]
If somebody found solution, please share it

**Comment by neSpecc** [comment]
Just use the `toolbox` [option](https://editorjs.io/getting-started/#available-tools-options) when connecting the tool.
