### ISSUE TITLE
Write escape character like & will return  &amp;

### ISSUE THREAD

**Issue by teneous** [editor-js/header#87]
When I write head named <React & balala> , the save method will return "`&lt;React &amp; balala &gt;`".
I guess use innerHtml is becuse it will pass inner node to backend.

But if I wanna pass & to backend rather than `&amp;`, is there any solution?

![image](https://user-images.githubusercontent.com/21994254/205433083-6b7b3f27-1813-4335-9be1-e0f53891e034.png)

**test page**

![image](https://user-images.githubusercontent.com/21994254/205433260-4a44ccda-383d-47e6-9e79-fd7170faac36.png)

**Comment by legezam** [comment]
@teneous , what was the solution in your particular case?
