### ISSUE TITLE
Multiple headings in the toolbox

### ISSUE THREAD

**Issue by Vinze** [editor-js/header#92]
On the homepage of Editor.js you can see multiple levels of headings in the screenshot, see:

![afbeelding](https://github.com/editor-js/header/assets/1716574/9ce8baa2-fb3c-4be2-8903-561c4d5e760f)

But after installing Editor.js and the header plugin I only have one "Heading" item in the toolbox. I found the following [pull request](https://github.com/editor-js/header/pull/79) but I guess this isn't merged into the default branch? When simply doing a `npm i --save @editorjs/header` I get the following:

![afbeelding](https://github.com/editor-js/header/assets/1716574/41783a40-07ad-41c6-9892-cd0937a68e6b)

How do I enable this feature?

**Comment by nhuanhoangduc** [comment]
Try creating a custom Header class
```
class CustomHeader extends Header {
  static get toolbox() {
    return [
      {
        icon: IconH1,
        title: 'Heading 1',
        data: {
          level: 1,
        },
      },
      {
        icon: IconH2,
        title: 'Heading 2',
        data: {
          level: 2,
        },
      },
      {
        icon: IconH3,
        title: 'Heading 3',
        data: {
          level: 3,
        },
      },
    ]
  }
}
```

**Comment by trig79** [comment]
this worked for me, depending on where you extend you may need to import the icons:
`import {IconH1, IconH2, IconH3} from '@codexteam/icons'`

**Comment by Vinze** [comment]
That seems to work, thank you!

Would be nice be able to configure this through an configuration option.

**Comment by TatianaFomina** [comment]
> That seems to work, thank you!
> 
> Would be nice be able to configure this through an configuration option.

There is such ability, read official article for more info 👉 https://codex.so/editorjs-toolbox
